project:
  type: book

book:
  title: "RP2040 Forth"
  author: "M. Edward (Ed) Borasky"
  date: "2022-07-21"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual

