project:
  type: book

book:
  title: "Raspberry Pi Pico Forth"
  author: "Jane Doe"
  date: "7/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

